apiVersion: 1

datasources:
  - name: Trino
    type: trino-datasource
    access: proxy
    url: http://trino:8080
    isDefault: false
    editable: true
    jsonData:
      catalog: iceberg
      schema: gold
